version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: "wordpress_mysql"
    ports:
      - "3307:3306"
    volumes:
      - ./sqldb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - my-bridge

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: "wordpress"
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
