version: '3.8'
services:
 mysqldb:
  restart: always
  image: mysql:5.7.16
  container_name: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=123456
  - MYSQL_USER=user
  - MYSQL_PASSWORD=password
  - MYSQL_DATABASE=database
  - TZ=Asia/Shanghai
  volumes:
  - ./mysql:/var/lib/mysql
  - ./mysql_config:/etc/mysql
  - ./conf/my.cnf:/etc/my.cnf